version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=ecommerce

  seed-script:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "seed"]
    environment:
      - PG_URL=postgres://dbuser:12345@db:5432/ecommerce
    depends_on:
      - db

  node-server:
    build: .
    environment:
      - PG_URL=postgres://dbuser:12345@db:5432/ecommerce
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    depends_on:
      - db
      - seed-script